a.out: main.cpp
	clang++ -std=c++26 -g main.cpp -llapack  -lmatplot -ljpeg -ltiff -lnodesoup -lz -lpng -o a.out

b.out: main2.cpp
	clang++ -I../include -std=c++26 -g main2.cpp -llapack  -lmatplot -ljpeg -ltiff -lnodesoup -lz -lpng -o b.out
